name: Deploy to Firebase App Hosting

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  GHOST_URL: ${{ secrets.GHOST_URL }}
  GHOST_KEY: ${{ secrets.GHOST_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        
      - name: Initialize App Hosting
        run: firebase init apphosting
        
      - name: Deploy to Firebase
        run: firebase deploy --only apphosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}